### ISSUE TITLE
[Bug]: last document page is not saved when closing the document

### ISSUE THREAD

**Issue by jdujava** [pwmt/zathura#701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Problem

In the develop branch (I pinpointed the commit c6e539b938877d2d223c5ed767c505c778d74e9d, where the regression seems to be introduced), the position in the document is not saved when closing the `zathura`. Opening the same document doesn't open the last seen page, but the one saved in database before the regression.

Also, launching zathura without any document and closing it throws the folowing:
```
** (org.pwmt.zathura:94322): CRITICAL **: 14:46:45.540: zathura_renderer_stop: assertion 'ZATHURA_IS_RENDERER(renderer)' failed

** (org.pwmt.zathura:94322): CRITICAL **: 14:46:45.540: zathura_db_set_fileinfo: assertion 'ZATHURA_IS_DATABASE(db) && file != NULL && hash_sha256 != NULL && file_info != NULL' failed

** (org.pwmt.zathura:94322): CRITICAL **: 14:46:45.541: zathura_db_save_jumplist: assertion 'ZATHURA_IS_DATABASE(db) && file != NULL && jumplist != NULL' failed

** (org.pwmt.zathura:94322): CRITICAL **: 14:46:45.541: zathura_db_save_quickmarks: assertion 'ZATHURA_IS_DATABASE(db) && file && quickmarks' failed
```

### Steps to reproduce

Open `zathura` without file, close it, and see the failed assertions.

Open `zathura` with file, scroll to some other page, remember it, and close the document. Open the same file again, and it will not scroll to the last seen page.

### Expected behavior

Database should be properly updated about the last seen document page.

### zathura version (zathura --version)

zathura 0.5.9

### girara version (zathura --version)

girara 0.4.5 (runtime: 0.4.5)

### zathura backend

poppler

**Comment by sebastinas** [comment]
I am unable to reproduce this issue. Could you set a break point in `zathura_renderer_stop` and provide us with the back trace?

**Comment by LostHopes** [comment]
Hey!
I've been facing the same issue on Arch testing

zathura 0.5.10
girara 0.4.5 (Runtime: 0.4.5)
gdb 15.2

# backtrace

```gdb

For help, type "help".
Type "apropos word" to search for commands related to "word"...
--Type <RET> for more, q to quit, c to continue without paging--
Reading symbols from zathura...
(gdb) break zathura_renderer_stop 
Breakpoint 1 at 0x169ef: file ../zathura/render.c, line 349.
(gdb) run ~/Downloads/CS.pdf 
Starting program: /home/losthope/Documents/University/Other/code-reading/zathura/build/zathura ~/Downloads/CS.pdf

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff33ff6c0 (LWP 302003)]
[New Thread 0x7fffea9ff6c0 (LWP 302004)]
[New Thread 0x7ffff2bfe6c0 (LWP 302005)]
[New Thread 0x7ffff1dff6c0 (LWP 302006)]
warning: Found no plugins. Please install at least one plugin.
[New Thread 0x7ffff09ff6c0 (LWP 302007)]
info: Opening plain database via sqlite backend.
info: No plain database available. Continuing with sqlite database.
error: Could not determine file type.
[Thread 0x7ffff09ff6c0 (LWP 302007) exited]
error: Could not determine file type.
error: Could not determine file type.
error: Could not determine file type.
error: Could not determine file type.
error: Could not determine file type.

Thread 1 "zathura" hit Breakpoint 1, zathura_renderer_stop (renderer=0x0) at ../zathura/render.c:349
349     void zathura_renderer_stop(ZathuraRenderer* renderer) {
(gdb) backtrace
#0  zathura_renderer_stop (renderer=0x0) at ../zathura/render.c:349
#1  0x0000555555575b11 in document_close (zathura=0x5555556f9d30, keep_monitor=false) at ../zathura/zathura.c:1429
#2  0x00005555555727d6 in zathura_free (zathura=0x5555556f9d30) at ../zathura/zathura.c:470
#3  0x00005555555634c7 in main (argc=2, argv=0x7fffffffe588) at ../zathura/main.c:300
(gdb) 
```

**Comment by sebastinas** [comment]
https://github.com/pwmt/zathura/commit/c6e539b938877d2d223c5ed767c505c778d74e9d#diff-7d2451a171e77e8c0fa91c8b91dcda08db445ac78c1afa7c0f50b07df199205bR1433 has an incorrect condition.
